title: "Объект всеобщей ненависти"
description: "Фанатский проект дубляжа и закадра аниме."
baseurl: "" 
url: "https://ovnanime.github.io/"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
