name: Deploy Jekyll without Docker

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build site
        run: bundle exec jekyll build --verbose --trace

      - name: Verify build
        run: |
          ls -la _site
          [ -f _site/index.html ] || exit 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
